version: '3.8'

services:
  app:
    container_name: raycast-unblock
    image: wibuswee/raycast-unblock:latest
    environment:
      - TZ=Asia/Shanghai
      - PORT=3000
      - HOST=0.0.0.0
      - AI_API_KEY=your_api_key
      - TRANSLATE_TYPE=ai
      # ### If you need to use .env file, please uncomment the following line ####
      # - ENV=./config/.env
    # ### If you need to use .env file, please uncomment the following line ####
    # volumes:
    #   - ./configs/raycast-unblock:/app/config
    ports:
      - '3000:3000'
    restart: always
    healthcheck:
      test: [CMD, curl, -f, 'http://127.0.0.1:3000']
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 30s
